NumPy

In [50]:
import numpy as np

In [51]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [52]:
arr.mean()

2.5

In [53]:
arr.max()

4

In [54]:
arr.min()

1

In [55]:
arr.size

4

In [56]:
arr.shape

(4,)

In [57]:
arr = arr.reshape([2,2])
arr

array([[1, 2],
       [3, 4]])

In [58]:
arr = np.linspace(1,10,20)
arr = arr.reshape(4,5)
arr

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [59]:
arr = arr.flatten()
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [60]:
# arr = np.split(arr,10)
arr

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [63]:
i = arr.argmax()
arr[i]

10.0

In [66]:
i = arr.argmin()
arr[i]

1.0

In [67]:
arr = np.round(arr)
arr

array([ 1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,
        7.,  8.,  8.,  9.,  9., 10., 10.])

In [90]:
arr = np.random.randint(10)
arr

1

In [94]:
arr = np.random.randint(10,size=(10,10))
arr

array([[5, 6, 6, 9, 7, 8, 7, 3, 8, 8],
       [7, 7, 5, 7, 6, 9, 6, 4, 9, 2],
       [5, 2, 6, 5, 9, 7, 4, 1, 5, 5],
       [8, 0, 8, 5, 5, 8, 3, 3, 1, 2],
       [9, 5, 3, 8, 2, 8, 6, 0, 0, 9],
       [3, 9, 4, 3, 6, 4, 5, 9, 2, 8],
       [1, 8, 9, 8, 9, 6, 9, 2, 0, 2],
       [1, 6, 3, 1, 6, 2, 0, 1, 1, 0],
       [9, 6, 2, 3, 5, 7, 9, 7, 8, 3],
       [4, 0, 6, 0, 9, 4, 5, 6, 6, 9]])

In [96]:
arr.sort()
arr

array([[3, 5, 6, 6, 7, 7, 8, 8, 8, 9],
       [2, 4, 5, 6, 6, 7, 7, 7, 9, 9],
       [1, 2, 4, 5, 5, 5, 5, 6, 7, 9],
       [0, 1, 2, 3, 3, 5, 5, 8, 8, 8],
       [0, 0, 2, 3, 5, 6, 8, 8, 9, 9],
       [2, 3, 3, 4, 4, 5, 6, 8, 9, 9],
       [0, 1, 2, 2, 6, 8, 8, 9, 9, 9],
       [0, 0, 1, 1, 1, 1, 2, 3, 6, 6],
       [2, 3, 3, 5, 6, 7, 7, 8, 9, 9],
       [0, 0, 4, 4, 5, 6, 6, 6, 9, 9]])

In [97]:
x = np.unique(arr)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])